### ISSUE TITLE
Data availability 

### ISSUE THREAD

**Issue by maclandrol** [pnnl/solubility-prediction-paper#1]
Hello @devcentral-pnnl 

I just read the [Predicting Aqueous Solubility of Organic Molecules Using Deep Learning Models with Varied Molecular Representations](https://arxiv.org/abs/2105.12638) paper, and I was wondering if you could share the data. 

I wasn't able to find it anywhere.

Thanks !

**Comment by gihanpanapitiya** [comment]
Hi maclandrol,

We have made available the part of our data with our updated publication at https://pubs.acs.org/doi/10.1021/acsomega.2c00642.

The rest of the data is at https://figshare.com/s/542fb80e65742746603c, but we have few problems with this link. This will be fixed soon.
